require File.expand_path("book_store/lib/book")
require File.expand_path("book_store/lib/easysale")
require File.expand_path("book_store/lib/report")
require File.expand_path("book_store/lib/database")
require File.expand_path("book_store/lib/dvd")
